from app.agent.tools._registry import tool

TEMPLATES = {
    "barbershop": {
        "nodes": [
            {"id": "node_1", "type": "start", "position": {"x": 250, "y": 50},
             "data": {"label": "Старт", "triggers": ["command:/start"]}},
            {"id": "node_2", "type": "text", "position": {"x": 250, "y": 200},
             "data": {"label": "Приветствие", "text": "Добро пожаловать в барбершоп! ✂️\nВыберите действие:"}},
            {"id": "node_3", "type": "buttons", "position": {"x": 250, "y": 350},
             "data": {"label": "Меню", "text": "Что вас интересует?",
                      "buttons": [
                          {"text": "📅 Записаться", "output_handle": "btn_book"},
                          {"text": "💈 Услуги и цены", "output_handle": "btn_prices"},
                          {"text": "📍 Адрес и время работы", "output_handle": "btn_address"},
                      ]}},
            {"id": "node_4", "type": "buttons", "position": {"x": 0, "y": 500},
             "data": {"label": "Выбор мастера", "text": "Выберите мастера:",
                      "buttons": [
                          {"text": "Алексей", "output_handle": "master_1"},
                          {"text": "Дмитрий", "output_handle": "master_2"},
                      ]}},
            {"id": "node_5", "type": "input", "position": {"x": 0, "y": 650},
             "data": {"label": "Имя", "text": "Как вас зовут?", "variable": "client_name"}},
            {"id": "node_6", "type": "input", "position": {"x": 0, "y": 800},
             "data": {"label": "Телефон", "text": "Ваш номер телефона:", "variable": "phone", "validation": "phone"}},
            {"id": "node_7", "type": "text", "position": {"x": 0, "y": 950},
             "data": {"label": "Подтверждение", "text": "Спасибо, {client_name}! Вы записаны. Мы позвоним по номеру {phone} для подтверждения."}},
            {"id": "node_8", "type": "text", "position": {"x": 250, "y": 500},
             "data": {"label": "Цены", "text": "💈 <b>Наши услуги:</b>\n\n• Стрижка — 1500₽\n• Борода — 800₽\n• Комплекс — 2000₽\n• Камуфляж седины — 1200₽"}},
            {"id": "node_9", "type": "text", "position": {"x": 500, "y": 500},
             "data": {"label": "Адрес", "text": "📍 <b>Адрес:</b> ул. Примерная, д. 1\n🕐 <b>Время работы:</b> 10:00–21:00, без выходных"}},
        ],
        "edges": [
            {"id": "e1", "source": "node_1", "target": "node_2"},
            {"id": "e2", "source": "node_2", "target": "node_3"},
            {"id": "e3", "source": "node_3", "target": "node_4", "sourceHandle": "btn_book"},
            {"id": "e4", "source": "node_3", "target": "node_8", "sourceHandle": "btn_prices"},
            {"id": "e5", "source": "node_3", "target": "node_9", "sourceHandle": "btn_address"},
            {"id": "e6", "source": "node_4", "target": "node_5", "sourceHandle": "master_1"},
            {"id": "e7", "source": "node_4", "target": "node_5", "sourceHandle": "master_2"},
            {"id": "e8", "source": "node_5", "target": "node_6"},
            {"id": "e9", "source": "node_6", "target": "node_7"},
        ],
        "viewport": {"x": 0, "y": 0, "zoom": 0.8},
    },
    "delivery": {
        "nodes": [
            {"id": "node_1", "type": "start", "position": {"x": 250, "y": 50},
             "data": {"label": "Старт", "triggers": ["command:/start"]}},
            {"id": "node_2", "type": "text", "position": {"x": 250, "y": 200},
             "data": {"label": "Приветствие", "text": "Добро пожаловать в службу доставки! 🚚"}},
            {"id": "node_3", "type": "buttons", "position": {"x": 250, "y": 350},
             "data": {"label": "Меню", "text": "Выберите категорию:",
                      "buttons": [
                          {"text": "🍕 Пицца", "output_handle": "cat_pizza"},
                          {"text": "🍔 Бургеры", "output_handle": "cat_burgers"},
                          {"text": "🥗 Салаты", "output_handle": "cat_salads"},
                      ]}},
            {"id": "node_4", "type": "input", "position": {"x": 250, "y": 500},
             "data": {"label": "Адрес доставки", "text": "Введите адрес доставки:", "variable": "address"}},
            {"id": "node_5", "type": "input", "position": {"x": 250, "y": 650},
             "data": {"label": "Телефон", "text": "Номер телефона для связи:", "variable": "phone"}},
            {"id": "node_6", "type": "text", "position": {"x": 250, "y": 800},
             "data": {"label": "Подтверждение", "text": "Заказ принят! 🎉\nДоставим по адресу: {address}\nСвяжемся с вами по номеру: {phone}"}},
        ],
        "edges": [
            {"id": "e1", "source": "node_1", "target": "node_2"},
            {"id": "e2", "source": "node_2", "target": "node_3"},
            {"id": "e3", "source": "node_3", "target": "node_4", "sourceHandle": "cat_pizza"},
            {"id": "e4", "source": "node_3", "target": "node_4", "sourceHandle": "cat_burgers"},
            {"id": "e5", "source": "node_3", "target": "node_4", "sourceHandle": "cat_salads"},
            {"id": "e6", "source": "node_4", "target": "node_5"},
            {"id": "e7", "source": "node_5", "target": "node_6"},
        ],
        "viewport": {"x": 0, "y": 0, "zoom": 0.8},
    },
    "online_school": {
        "nodes": [
            {"id": "node_1", "type": "start", "position": {"x": 250, "y": 50},
             "data": {"label": "Старт", "triggers": ["command:/start"]}},
            {"id": "node_2", "type": "text", "position": {"x": 250, "y": 200},
             "data": {"label": "Приветствие", "text": "Добро пожаловать в онлайн-школу! 🎓\nЗдесь вы найдёте лучшие курсы."}},
            {"id": "node_3", "type": "buttons", "position": {"x": 250, "y": 350},
             "data": {"label": "Меню", "text": "Что вас интересует?",
                      "buttons": [
                          {"text": "📚 Каталог курсов", "output_handle": "btn_catalog"},
                          {"text": "🎁 Бесплатный урок", "output_handle": "btn_free"},
                          {"text": "💬 Задать вопрос", "output_handle": "btn_question"},
                      ]}},
            {"id": "node_4", "type": "text", "position": {"x": 0, "y": 500},
             "data": {"label": "Каталог", "text": "📚 <b>Наши курсы:</b>\n\n1. Python с нуля — 4990₽\n2. Web-разработка — 7990₽\n3. Data Science — 9990₽\n\nНапишите номер курса для подробностей."}},
            {"id": "node_5", "type": "input", "position": {"x": 250, "y": 500},
             "data": {"label": "Email", "text": "Отлично! Введите ваш email для получения бесплатного урока:", "variable": "email", "validation": "email"}},
            {"id": "node_6", "type": "text", "position": {"x": 250, "y": 650},
             "data": {"label": "Урок отправлен", "text": "Бесплатный урок отправлен на {email}! 🎉\nПроверьте почту."}},
            {"id": "node_7", "type": "input", "position": {"x": 500, "y": 500},
             "data": {"label": "Вопрос", "text": "Напишите ваш вопрос, и мы ответим в ближайшее время:", "variable": "question"}},
            {"id": "node_8", "type": "text", "position": {"x": 500, "y": 650},
             "data": {"label": "Вопрос получен", "text": "Спасибо за вопрос! Мы ответим вам в течение 24 часов. 📩"}},
        ],
        "edges": [
            {"id": "e1", "source": "node_1", "target": "node_2"},
            {"id": "e2", "source": "node_2", "target": "node_3"},
            {"id": "e3", "source": "node_3", "target": "node_4", "sourceHandle": "btn_catalog"},
            {"id": "e4", "source": "node_3", "target": "node_5", "sourceHandle": "btn_free"},
            {"id": "e5", "source": "node_3", "target": "node_7", "sourceHandle": "btn_question"},
            {"id": "e6", "source": "node_5", "target": "node_6"},
            {"id": "e7", "source": "node_7", "target": "node_8"},
        ],
        "viewport": {"x": 0, "y": 0, "zoom": 0.8},
    },
    "support": {
        "nodes": [
            {"id": "node_1", "type": "start", "position": {"x": 250, "y": 50},
             "data": {"label": "Старт", "triggers": ["command:/start"]}},
            {"id": "node_2", "type": "text", "position": {"x": 250, "y": 200},
             "data": {"label": "Приветствие", "text": "Здравствуйте! Я бот поддержки. 🤖\nЧем могу помочь?"}},
            {"id": "node_3", "type": "buttons", "position": {"x": 250, "y": 350},
             "data": {"label": "Категория", "text": "Выберите тему обращения:",
                      "buttons": [
                          {"text": "🔧 Техническая проблема", "output_handle": "btn_tech"},
                          {"text": "💳 Вопрос по оплате", "output_handle": "btn_payment"},
                          {"text": "📦 Статус заказа", "output_handle": "btn_order"},
                      ]}},
            {"id": "node_4", "type": "input", "position": {"x": 250, "y": 500},
             "data": {"label": "Описание проблемы", "text": "Опишите вашу проблему:", "variable": "issue_text"}},
            {"id": "node_5", "type": "text", "position": {"x": 250, "y": 650},
             "data": {"label": "Тикет создан", "text": "Обращение принято! Номер тикета: #BF{chat_id}\nМы ответим в течение 2 часов."}},
        ],
        "edges": [
            {"id": "e1", "source": "node_1", "target": "node_2"},
            {"id": "e2", "source": "node_2", "target": "node_3"},
            {"id": "e3", "source": "node_3", "target": "node_4", "sourceHandle": "btn_tech"},
            {"id": "e4", "source": "node_3", "target": "node_4", "sourceHandle": "btn_payment"},
            {"id": "e5", "source": "node_3", "target": "node_4", "sourceHandle": "btn_order"},
            {"id": "e6", "source": "node_4", "target": "node_5"},
        ],
        "viewport": {"x": 0, "y": 0, "zoom": 0.8},
    },
    "lead_funnel": {
        "nodes": [
            {"id": "node_1", "type": "start", "position": {"x": 250, "y": 50},
             "data": {"label": "Старт", "triggers": ["command:/start"]}},
            {"id": "node_2", "type": "text", "position": {"x": 250, "y": 200},
             "data": {"label": "Лид-магнит", "text": "🎁 Получите бесплатный чек-лист!\nОтветьте на 3 вопроса."}},
            {"id": "node_3", "type": "input", "position": {"x": 250, "y": 350},
             "data": {"label": "Имя", "text": "Как вас зовут?", "variable": "name"}},
            {"id": "node_4", "type": "input", "position": {"x": 250, "y": 500},
             "data": {"label": "Email", "text": "Ваш email для отправки чек-листа:", "variable": "email", "validation": "email"}},
            {"id": "node_5", "type": "input", "position": {"x": 250, "y": 650},
             "data": {"label": "Телефон", "text": "Номер телефона (необязательно, но мы перезвоним):", "variable": "phone"}},
            {"id": "node_6", "type": "text", "position": {"x": 250, "y": 800},
             "data": {"label": "Спасибо", "text": "Спасибо, {name}! 🎉\nЧек-лист отправлен на {email}.\nМы свяжемся с вами в ближайшее время!"}},
        ],
        "edges": [
            {"id": "e1", "source": "node_1", "target": "node_2"},
            {"id": "e2", "source": "node_2", "target": "node_3"},
            {"id": "e3", "source": "node_3", "target": "node_4"},
            {"id": "e4", "source": "node_4", "target": "node_5"},
            {"id": "e5", "source": "node_5", "target": "node_6"},
        ],
        "viewport": {"x": 0, "y": 0, "zoom": 0.8},
    },
    "quiz": {
        "nodes": [
            {"id": "node_1", "type": "start", "position": {"x": 250, "y": 50},
             "data": {"label": "Старт", "triggers": ["command:/start"]}},
            {"id": "node_2", "type": "text", "position": {"x": 250, "y": 200},
             "data": {"label": "Начало квиза", "text": "🎯 Пройдите квиз и получите персональную рекомендацию!"}},
            {"id": "node_3", "type": "buttons", "position": {"x": 250, "y": 350},
             "data": {"label": "Вопрос 1", "text": "Вопрос 1/3: Ваш бюджет?",
                      "buttons": [
                          {"text": "До 10 000₽", "output_handle": "budget_low"},
                          {"text": "10 000 — 50 000₽", "output_handle": "budget_mid"},
                          {"text": "Более 50 000₽", "output_handle": "budget_high"},
                      ]}},
            {"id": "node_4", "type": "buttons", "position": {"x": 250, "y": 500},
             "data": {"label": "Вопрос 2", "text": "Вопрос 2/3: Когда нужен результат?",
                      "buttons": [
                          {"text": "Срочно", "output_handle": "time_urgent"},
                          {"text": "В течение месяца", "output_handle": "time_month"},
                          {"text": "Не спешу", "output_handle": "time_no_rush"},
                      ]}},
            {"id": "node_5", "type": "input", "position": {"x": 250, "y": 650},
             "data": {"label": "Контакт", "text": "Вопрос 3/3: Ваш email для отправки результата:", "variable": "email"}},
            {"id": "node_6", "type": "text", "position": {"x": 250, "y": 800},
             "data": {"label": "Результат", "text": "Квиз пройден! 🎉\nРезультат отправлен на {email}."}},
        ],
        "edges": [
            {"id": "e1", "source": "node_1", "target": "node_2"},
            {"id": "e2", "source": "node_2", "target": "node_3"},
            {"id": "e3", "source": "node_3", "target": "node_4", "sourceHandle": "budget_low"},
            {"id": "e4", "source": "node_3", "target": "node_4", "sourceHandle": "budget_mid"},
            {"id": "e5", "source": "node_3", "target": "node_4", "sourceHandle": "budget_high"},
            {"id": "e6", "source": "node_4", "target": "node_5", "sourceHandle": "time_urgent"},
            {"id": "e7", "source": "node_4", "target": "node_5", "sourceHandle": "time_month"},
            {"id": "e8", "source": "node_4", "target": "node_5", "sourceHandle": "time_no_rush"},
            {"id": "e9", "source": "node_5", "target": "node_6"},
        ],
        "viewport": {"x": 0, "y": 0, "zoom": 0.8},
    },
    "appointment": {
        "nodes": [
            {"id": "node_1", "type": "start", "position": {"x": 250, "y": 50},
             "data": {"label": "Старт", "triggers": ["command:/start"]}},
            {"id": "node_2", "type": "text", "position": {"x": 250, "y": 200},
             "data": {"label": "Приветствие", "text": "Здравствуйте! Запишитесь на приём. 📅"}},
            {"id": "node_3", "type": "input", "position": {"x": 250, "y": 350},
             "data": {"label": "ФИО", "text": "Ваше ФИО:", "variable": "full_name"}},
            {"id": "node_4", "type": "input", "position": {"x": 250, "y": 500},
             "data": {"label": "Телефон", "text": "Номер телефона:", "variable": "phone", "validation": "phone"}},
            {"id": "node_5", "type": "buttons", "position": {"x": 250, "y": 650},
             "data": {"label": "Время", "text": "Выберите удобное время:",
                      "buttons": [
                          {"text": "Утро (9:00–12:00)", "output_handle": "time_morning"},
                          {"text": "День (12:00–17:00)", "output_handle": "time_afternoon"},
                          {"text": "Вечер (17:00–20:00)", "output_handle": "time_evening"},
                      ]}},
            {"id": "node_6", "type": "text", "position": {"x": 250, "y": 800},
             "data": {"label": "Подтверждение", "text": "Вы записаны, {full_name}! ✅\nМы позвоним по номеру {phone} для подтверждения."}},
        ],
        "edges": [
            {"id": "e1", "source": "node_1", "target": "node_2"},
            {"id": "e2", "source": "node_2", "target": "node_3"},
            {"id": "e3", "source": "node_3", "target": "node_4"},
            {"id": "e4", "source": "node_4", "target": "node_5"},
            {"id": "e5", "source": "node_5", "target": "node_6", "sourceHandle": "time_morning"},
            {"id": "e6", "source": "node_5", "target": "node_6", "sourceHandle": "time_afternoon"},
            {"id": "e7", "source": "node_5", "target": "node_6", "sourceHandle": "time_evening"},
        ],
        "viewport": {"x": 0, "y": 0, "zoom": 0.8},
    },
}


@tool(
    name="apply_template",
    description="Загрузить готовый шаблон бота (barbershop, delivery, online_school, support, lead_funnel, quiz, appointment)",
    parameters={
        "type": "object",
        "properties": {
            "template_name": {
                "type": "string",
                "enum": list(TEMPLATES.keys()),
                "description": "Название шаблона",
            },
        },
        "required": ["template_name"],
    },
    is_write=True,
)
async def apply_template(schema: dict, template_name: str) -> dict:
    template = TEMPLATES.get(template_name)
    if not template:
        return {"error": f"Шаблон '{template_name}' не найден. Доступные: {list(TEMPLATES.keys())}"}

    schema["nodes"] = [dict(n) for n in template["nodes"]]
    schema["edges"] = [dict(e) for e in template["edges"]]
    schema["viewport"] = dict(template.get("viewport", {"x": 0, "y": 0, "zoom": 1}))

    return {
        "status": "template_applied",
        "template": template_name,
        "nodes_count": len(schema["nodes"]),
        "edges_count": len(schema["edges"]),
    }
